tap "getantibody/tap"
tap "heroku/brew"
tap "homebrew/apache"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/php"
tap "homebrew/services"
tap "homebrew/versions"
cask "java"
brew "adns"
brew "libyaml"
brew "openssl"
brew "python@2"
brew "ansible"
brew "python"
brew "ansible-lint"
brew "asciinema"
brew "autoconf"
brew "awscli"
brew "bash"
brew "bat"
brew "blueutil"
brew "cgal"
brew "cmake"
brew "colordiff"
brew "consul"
brew "coreutils"
brew "ctags"
brew "curl", args: ["with-openssl"]
brew "diff-so-fancy"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "docker-clean"
brew "doitlive"
brew "jpeg"
brew "elixir"
brew "exa"
brew "fd"
brew "freexl"
brew "fzf"
brew "gawk"
brew "giflib"
brew "json-c"
brew "lzlib"
brew "proj"
brew "libgeotiff"
brew "libspatialite"
brew "gdal"
brew "geoip"
brew "gettext", link: true
brew "git"
brew "gnu-tar"
brew "gnupg"
brew "gpg-agent"
brew "libtool"
brew "graphviz"
brew "hadolint"
brew "lua"
brew "highlight"
brew "htop"
brew "libevent"
brew "zlib"
brew "httpd", args: ["with-mpm-event", "with-privileged-ports"]
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jo"
brew "jpegoptim"
brew "jq"
brew "kompose"
brew "libidn2"
brew "liblwgeom"
brew "libpq"
brew "libusb-compat"
brew "mas"
brew "mercurial"
brew "mongodb"
brew "mysql"
brew "nano"
brew "nmap"
brew "nvm"
brew "optipng"
brew "pandoc"
brew "postgresql", restart_service: true
brew "pgcli"
brew "php@5.6", args: ["with-homebrew-curl"]
brew "pinentry-mac"
brew "sfcgal"
brew "postgis"
brew "pyenv"
brew "qt"
brew "rabbitmq"
brew "redis"
brew "rmtrash"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "ssh-copy-id"
brew "swig"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tig"
brew "tinc"
brew "tokei"
brew "travis"
brew "tree"
brew "ttyrec"
brew "ttygif"
brew "vim"
brew "wget"
brew "z"
brew "zsh"
brew "getantibody/tap/antibody"
brew "heroku/brew/heroku"
cask "enpass"
cask "flux"
cask "font-consolas-for-powerline"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-inconsolata-for-powerline"
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
cask "keyboard-cleaner"
cask "lastfm"
cask "netbeans"
cask "pgadmin4"
cask "postman"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "skype"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "wkhtmltopdf"
mas "App Cleaner", id: 1013897218
mas "CopyClip", id: 595191960
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SimpleCleaner", id: 867373024
mas "Telegram Desktop", id: 946399090
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
