tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "adns"
brew "autoconf"
brew "bash"
brew "blueutil"
brew "gettext", link: true
brew "readline"
brew "sqlite"
brew "python"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "curl"
brew "diff-so-fancy"
brew "docker-clean"
brew "jpeg"
brew "elixir"
brew "fd"
brew "fzf"
brew "gawk"
brew "git"
brew "libevent"
brew "libidn2"
brew "gnutls"
brew "libgcrypt"
brew "libksba"
brew "npth"
brew "gnupg"
brew "gpgme"
brew "lua"
brew "highlight"
brew "ilmbase"
brew "libde265"
brew "shared-mime-info"
brew "libheif"
brew "libomp"
brew "libtool"
brew "little-cms2"
brew "openexr"
brew "openjpeg"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "libgeotiff"
brew "libpq"
brew "libxml2"
brew "libyaml"
brew "mas"
brew "mysql-client"
brew "nano"
brew "node"
brew "nvm"
brew "optipng"
brew "pandoc"
brew "pgcli"
brew "pinentry-mac"
brew "postgresql@9.6", restart_service: true
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "ruby"
brew "rustup-init"
brew "swig"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "wget"
brew "z"
brew "zlib"
brew "zsh"
brew "getantibody/tap/antibody"
cask "brave-browser"
cask "enpass"
cask "flux"
cask "font-consolas-for-powerline"
cask "font-fira-code"
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
cask "hyper"
cask "keyboard-cleaner"
cask "maccy"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "sequel-pro"
cask "skype"
cask "spectacle"
cask "spotify"
cask "tableplus"
cask "the-unarchiver"
cask "visual-studio-code"
cask "wkhtmltopdf"
cask "zoomus"
mas "Cleaner-App", id: 1013897218
mas "Dato", id: 1470584107
mas "HazeOver", id: 430798174
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "Xcode", id: 497799835
