#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Exporting the specific shell we want to work with:

SHELL='/bin/bash'
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
# Set BASEDIR to the directory where this script is located
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly DOTBOT_ARGS="$@"

cd "$BASEDIR"
if git submodule status | grep -q '^+'; then
  git submodule sync --quiet --recursive
fi
if git submodule foreach 'git status --porcelain' | grep -q '^'; then
  git submodule update --init --recursive
fi

# Linking dotfiles:

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    -c "$config" $DOTBOT_ARGS

  source ~/.bash_profile
}

run_dotbot 'steps/terminal.yml' || true
run_dotbot 'steps/dependencies.yml' || true
# run_dotbot 'steps/vscode.yml' || true
# run_dotbot 'steps/streamdeck.yml' || true
