#!/usr/bin/env bash

set -e

# Exporting the specific shell we want to work with:

SHELL='/bin/bash'
export SHELL

# Standard dotbot pre-configuration:

DOTBOT_DIR='dotbot'

DOTBOT_BIN='bin/dotbot'
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ARGS="${@}"

cd "${BASEDIR}"
git submodule update --init --recursive

# Linking dotfiles:

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    --plugin-dir dotbot-pip \
    -c "$config" "$ARGS"
}

run_dotbot 'steps/terminal.yml'

run_dotbot 'steps/codespaces.yml'
source "$HOME/.shell/.codespaces"

run_dotbot 'steps/dependencies.yml'
run_dotbot 'steps/vscode.yml'
