code --install-extension alexdima.copy-relative-path
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension dariofuzinato.vue-peek
code --install-extension EditorConfig.EditorConfig
code --install-extension justusadam.language-haskell
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-python.python
code --install-extension ms-vscode.sublime-keybindings
code --install-extension octref.vetur
code --install-extension rust-lang.rust
code --install-extension stevejpurves.cucumber
code --install-extension teabyii.ayu
