#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
if [ -d "$HOME/.linuxbrew" ]; then
  # codespaces
  eval $($HOME/.linuxbrew/bin/brew shellenv)
else
  # mac
  PATH="/usr/local/bin:$PATH"
  export PATH
fi
