#!/usr/bin/env bash

# I do not use bash directly.
# So this file only includes `brew` binaries.

# global:
PATH="/opt/homebrew/bin:/usr/local/bin::/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
export PATH
