#!/usr/bin/env bash

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.external"


# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi
