#!/usr/bin/env zsh

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

# === Plugin management ===

ZPLUG_HOME=${ZPLUG_HOME:-'/usr/local/opt/zplug'}
export ZPLUG_HOME
source "$HOME/.zplugrc"


# === Shell parts ===

source "$HOME/.shell/.codespaces"
source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.external"


# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi
