# This file is sourced for all shells, not just interactive ones like `.zshrc`.

_fzf_complete_realpath() {
  # Used for `tab` completion in `shell/.completions` and `shell/.external`.
  # Can be customized to behave differently for different objects.
  local realpath="$1"
  if [ -d "$realpath" ]; then
    tree -a -I '.DS_Store|.localized' -C "$realpath" | head -100
  else
    mime="$(file -Lbs --mime-type "$realpath")"
    category="${mime%%/*}"
    if [ "$category" = 'image' ]; then
      # I guessed `60` to be fine for my exact terminal size
      local default_width=$(( "$FZF_PREVIEW_COLUMNS" < 60 ? 60 : "$FZF_PREVIEW_COLUMNS" ))
      catimg -r2 -w "$default_width" "$realpath"
    else
      bat -n --color=always --line-range :100 --theme=GitHub "$realpath"
    fi
  fi
}
