# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
ZSH="$HOME/.oh-my-zsh"

# for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
# 	[ -r "$file" ] && [ -f "$file" ] && source "$file";
# done;
# unset file;

# If you come from bash you might have to change your $PATH.
#GOPATH MUST BE OUTSIDE OF GOROOT directory!!!
# GVM_ROOT="$HOME/.gvm"
# GVM_GOROOT="$GVM_ROOT/gos/go1.23.2"
GOPATH="${HOME}/go"
GOBIN="$GOPATH/bin"
GOROOT="/usr/local/go/"
# JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
# export PATH=$PATH:$JAVA_HOME/bin
VENV_PATH="$HOME/dev/.virtual-env/"
PATH="$HOME/bin:/opt/homebrew/bin:/usr/local/bin:$GOPATH/bin:$GOROOT/bin:$GOBIN:$VENV_PATH:$PATH"

export GO111MODULE=on

export ZSH

export PATH

figlet -f ogre '{ be open to }'
echo -e "\e[1;4;36m Learn, \e[1;4;33m Unlearn,\e[0m \e[1;4;35m Relearn\e[2m. \e[1m Coz knowledge is Power...\e[0m"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="agnoster"
# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Theme is set via `zplug`, see `config/zplugrc`.
# ZSH_THEME="sobole"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE='false'

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE='false'

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="false"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS='yyyy-mm-dd'

# Commands starting from " " (whitespace) won't be saved in history:
HIST_IGNORE_SPACE='true'

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(
  gitfast
  gh
  git 
  colored-man-pages 
  colorize 
  pip 
  python 
  brew 
  macos 
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Sourcing the Oh-My-ZSH source:
source "$ZSH/oh-my-zsh.sh"


# === Plugin management ===

# ZPLUG_HOME='/opt/homebrew/opt/zplug'
# export ZPLUG_HOME
# source "$HOME/.zplugrc"


# === Shell parts ===

source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
# source "$HOME/.shell/.external"
# source "$HOME/.shell/.completions"


# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh